[package]
name = "tales-of-ssl"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
base64 = "0.22.1"
celes = "2.6.0"
dotenvy_macro = "0.15.7"
openssl = "0.10.74"
reqwest = { version = "0.12.24", features = ["json", "blocking"] }
serde = "1.0.228"
serde_json = "1.0.145"
